FROM node:20-alpine3.20@sha256:fabde88b0d0e5fe3ee2f61c3e5b74b4b48aa7541da887b95dcb61305d8b4e24 AS deps
WORKDIR /app
# Don't use apk upgrade as it can introduce variability
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-alpine3.20@sha256:fabde88b0d0e5fe3ee2f61c3e5b74b4b48aa7541da887b95dcb61305d8b4e24 AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine3.20@sha256:fabde88b0d0e5fe3ee2f61c3e5b74b4b48aa7541da887b95dcb61305d8b4e24 AS runner
WORKDIR /app
ENV NODE_ENV=production
# Don't use apk upgrade - add specific packages only
RUN apk add --no-cache curl wget dumb-init
RUN rm -rf /usr/local/lib/node_modules/npm /usr/local/bin/npm /usr/local/bin/npx
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "server.js"]
